/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello;

import java.awt.Graphics;
import static othello.Board.SIDE_LENGTH;

/**
 *
 * @author shirdav18
 */
public class Board extends javax.swing.JPanel {

    private Piece[][] gameBoard;
    public static final int SIDE_LENGTH = 8;
    private static int whiteCount;
    private static int blackCount;
    //keep track of whose turn it is?
    
    public Board() {
        initComponents();
        gameBoard = new Piece[SIDE_LENGTH][SIDE_LENGTH];
        initializeStart();
    }
    
    private void initializeStart() {
        gameBoard[3][3] = new Piece("white");
        gameBoard[4][4] = new Piece("white");
        gameBoard[3][4] = new Piece("black");
        gameBoard[4][3] = new Piece("black");
        whiteCount += 2;
        blackCount += 2;
    }
    
    public void addPiece(int x, int y, String color) {
        gameBoard[x][y] = new Piece(color);
        
    }
    
    public boolean spaceEmpty(int x, int y) {
        
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < Board.SIDE_LENGTH; i++) {
            g.drawLine(125 * i, 0, 125 * i, MainFrame.SIDE_LENGTH);
            g.drawLine(0, 125 * i, MainFrame.SIDE_LENGTH, 125 * i);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
