/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello;

import java.awt.Graphics;

/**
 *
 * @author shirdav18
 */
public class HomeScreen extends javax.swing.JPanel {

    private MainFrame parent;
    
    public HomeScreen(MainFrame jf) {
        parent = jf;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        twoPlayerBtn = new javax.swing.JButton();
        howToPlayBtn = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Cambria", 0, 72)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("OTHELLO");

        twoPlayerBtn.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        twoPlayerBtn.setText("TWO PLAYER");
        twoPlayerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoPlayerBtnMouseClicked(evt);
            }
        });
        twoPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPlayerBtnActionPerformed(evt);
            }
        });

        howToPlayBtn.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        howToPlayBtn.setText("HOW TO PLAY");
        howToPlayBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howToPlayBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(twoPlayerBtn)
                        .addGap(47, 47, 47)
                        .addComponent(howToPlayBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(titleLabel)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(titleLabel)
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoPlayerBtn)
                    .addComponent(howToPlayBtn))
                .addContainerGap(437, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void twoPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPlayerBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_twoPlayerBtnActionPerformed

    private void twoPlayerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoPlayerBtnMouseClicked
        parent.switchScreen("game");
    }//GEN-LAST:event_twoPlayerBtnMouseClicked

    private void howToPlayBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToPlayBtnMouseClicked
        parent.switchScreen("htp");
    }//GEN-LAST:event_howToPlayBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton howToPlayBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton twoPlayerBtn;
    // End of variables declaration//GEN-END:variables
}
